---
- import_tasks: os_setup.yml
  become: true
  tags:
    - os_setup

- import_tasks: custom_shell.yml
  when: install_custom_shell
  tags:
    - custom_shell

- import_tasks: tailscale.yml
  become: true
  when: install_tailscale
  tags:
    - tailscale

- import_tasks: pihole.yml
  when: install_pihole
  tags:
    - pihole

- import_tasks: proxy.yml
  become: true
  notify:
    - reload php-fpm
    - reload nginx
  tags:
    - proxy
    - nginx
