---
- import_tasks: rpi_setup.yml
  become: true
  tags:
    - rpi_setup

- name: Get installed php-fpm version
  shell: ls /lib/systemd/system/ | sed -nr 's/^(php.*fpm)\.service$/\1/p'
  register: php_fpm_version
  changed_when: false
  tags:
    - always

- import_tasks: custom_shell.yml
  when: customize_shell
  tags:
    - custom_shell

- import_tasks: pihole.yml
  when: pihole_enable
  tags:
    - pihole

- import_tasks: server.yml
  become: true
  notify:
    - reload php-fpm
    - reload nginx
  tags:
    - server
    - nginx
