---
- import_tasks: os_setup.yml
  become: true
  tags:
    - os_setup

- import_tasks: custom_shell.yml
  when: install_custom_shell
  tags:
    - custom_shell

- import_tasks: tailscale.yml
  become: true
  when: tailscale_install
  tags:
    - tailscale

- import_tasks: docker.yml
  become: true
  tags:
    - docker

- import_tasks: pihole.yml
  become: true
  when: pihole_install
  tags:
    - pihole

- import_tasks: home_assistant.yml
  become: true
  when: hast_install
  tags:
    - home_assistant
    - hast

- import_tasks: proxy.yml
  become: true
  when: proxy_install
  tags:
    - proxy
