---
- name: Update packages
  apt:
    update_cache: true
    cache_valid_time: 3600
    upgrade: true
    autoclean: true
    autoremove: true
  tags:
    - update_packages

# do_boot_behaviour: B1 cli, B2 cli autologin, B3 desktop, B4 desktop autologin
- name: Set raspi-config settings
  shell: |
    raspi-config nonint do_boot_behaviour B2
    raspi-config nonint do_change_locale {{ rpi_locale }}
    raspi-config nonint do_wifi_country {{ rpi_wifi_country }}
    raspi-config nonint do_change_timezone {{ rpi_timezone }}
    raspi-config nonint do_configure_keyboard {{ rpi_kb_layout }}
  tags:
    - host_setup

- name: Set authorized keys from url
  ansible.posix.authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key: "{{ ssh_public_key_url }}"
  tags:
    - user_setup

- name: Set hostname {{ rpi_hostname }}
  hostname:
    name: "{{ rpi_hostname }}"
  tags:
    - host_setup

- name: Update /etc/hosts
  template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: "0644"
  tags:
    - host_setup

- name: Install basic build packages
  apt:
    pkg:
      - make
      - cmake
      - build-essential
      - man
      - wget
      - curl
      - gzip
      - gnupg2
      - coreutils
      - libffi-dev
      - libssl-dev
      - python3-dev
      - python3-pip
      - python3-passlib
      - apt-transport-https
      - software-properties-common
      - ca-certificates
      - command-not-found
      - apache2-utils
      - pkg-config
      - autoconf
      - bison
      - zlib1g-dev
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
      - libseccomp2
      - sqlite3
      - llvm
      - libncurses-dev
      - xz-utils
      - tk-dev
      - liblzma-dev
      - libyaml-dev
    state: latest
  tags:
    - update_packages

- name: Install more packages
  apt:
    pkg:
      - zsh
      - tmux
      - htop
      - less
      - tree
      - xclip
      - xsel
      - vim
      - vim-gui-common
      - rsync
      - git
      - ufw
      - dnsutils
      - net-tools
      - netcat-openbsd
      - telnet
      - lsof
      - nmap
      - openssh-client
      - openssh-server
      - imagemagick
      - atomicparsley
      - ffmpeg
      - cloc
      - fzf
      - ripgrep
      - fonts-powerline
      - fonts-firacode
      - grc
      - certbot
    state: latest
  tags:
    - update_packages

- name: Install packages from url
  apt:
    deb: "{{ item }}"
    state: present
  with_items:
    - https://github.com/sharkdp/bat/releases/download/v{{ install_bat_version }}/bat_{{ install_bat_version }}_arm64.deb
    - https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-arm64.deb
    - https://github.com/fastfetch-cli/fastfetch/releases/latest/download/fastfetch-linux-aarch64.deb
  tags:
    - update_packages
    - update_cloudflared
  notify:
    - restart cloudflared

# check using `cat /proc/sys/vm/swappiness`
- name: Set Swappiness
  ansible.posix.sysctl:
    name: vm.swappiness
    value: "20"
    state: present
  tags:
    - set_sysctl

# check using `cat /proc/sys/fs/inotify/max_user_watches`
- name: Set inotify max_user_watches
  ansible.posix.sysctl:
    name: fs.inotify.max_user_watches
    value: "65536"
    state: present
  tags:
    - set_sysctl

- name: Setup UFW firewall
  community.general.ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  with_items:
    - { port: ssh, proto: tcp } # port 22
    - { port: 80, proto: tcp } # HTTP
    - { port: 443, proto: tcp } # HTTPS
    - { port: 53, proto: tcp } # DNS tcp
    - { port: 53, proto: udp } # DNS udp
    - { port: 67, proto: tcp } # DHCP tcp
    - { port: 67, proto: udp } # DHCP udp
    - { port: "546:547", proto: udp } # DHCPv6
  tags:
    - setup_firewall

- name: Enable UFW
  community.general.ufw:
    state: enabled
  tags:
    - setup_firewall
