---
- name: Add custom DNS list to Pi-hole
  template:
    src: pihole/custom.list.j2
    dest: "{{ docker_shared_dir }}/pihole/etc-pihole/custom.list"
    mode: "0644"
  become: true
  tags:
    - pihole_configure
    - tailscale_configure

- name: Add custom adlists to Pi-hole
  shell: sqlite3 "{{ docker_shared_dir }}/pihole/etc-pihole/gravity.db" "INSERT or IGNORE INTO adlist(address) values('{{ item }}');"
  with_items: "{{ pihole_adlist }}"
  become: true
  tags:
    - pihole_configure

- name: Add custom allowlist to Pi-hole
  shell: sqlite3 "{{ docker_shared_dir }}/pihole/etc-pihole/gravity.db" "INSERT or IGNORE INTO domainlist(domain,type) values('{{ item }}',0);"
  with_items: "{{ pihole_allowlist }}"
  become: true
  tags:
    - pihole_configure

- name: Update gravity database
  community.docker.docker_container_exec:
    container: pihole
    command: pihole -g
  register: gravity_result
  tags:
    - pihole_configure
    - pihole_update

- name: Update gravity result
  debug:
    var: gravity_result.stdout
  tags:
    - never
    - pihole_update
