---
- name: Add traefik config file
  template:
    src: proxy/traefik.yml
    dest: "{{ docker_shared_dir }}/traefik/traefik.yml"
    mode: "0644"
  notify:
    - restart proxy
  tags:
    - proxy_configure
    - compose

- name: Create a proxy-auth.htpasswd file
  community.general.htpasswd:
    path: "{{ docker_shared_dir }}/traefik/proxy-auth.htpasswd"
    name: "{{ proxy_auth_user }}"
    password: "{{ proxy_auth_password }}"
    crypt_scheme: bcrypt
    owner: root
    group: root
    mode: 0640
  notify:
    - restart proxy
  tags:
    - proxy_configure
    - compose
