---
- name: Add traefik config files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0644"
  with_items:
    - { src: proxy/traefik.yml, dest: "{{ docker_shared_dir }}/traefik/traefik.yml" }
    - { src: proxy/file-provider.yml, dest: "{{ docker_shared_dir }}/traefik/file-provider.yml" }
  notify:
    - restart proxy
  tags:
    - proxy_configure
    - compose

- name: Create a proxy-auth.htpasswd file
  community.general.htpasswd:
    path: "{{ docker_shared_dir }}/traefik/proxy-auth.htpasswd"
    name: "{{ proxy_auth_user }}"
    password: "{{ proxy_auth_password }}"
    crypt_scheme: bcrypt
    owner: root
    group: root
    mode: 0640
  notify:
    - restart proxy
  tags:
    - proxy_configure
    - compose
