---
- name: Update nginx conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: "0644"

- name: Update pihole nginx virtual conf
  template:
    src: nginx_pihole.conf.j2
    dest: /etc/nginx/conf.d/pihole.conf
    owner: root
    group: root
    mode: "0644"
  when: pihole_enable

- name: Set file permissions for nginx
  file:
    path: /var/www/html
    state: directory
    owner: www-data
    group: www-data
    mode: "0755"
    recurse: true

- name: Add www-data to pihole group
  user:
    name: www-data
    groups:
      - pihole
      - www-data
    append: true
  when: pihole_enable
