---
- name: Add tailscale apt key for debian {{ ansible_distribution_release }}
  apt_key:
    url: "https://pkgs.tailscale.com/stable/debian/{{ ansible_distribution_release|lower }}.noarmor.gpg"
    keyring: /usr/share/keyrings/tailscale-archive-keyring.gpg
    state: present
  tags:
    - update_packages

- name: Add tailscale repo for debian {{ ansible_distribution_release }}
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/tailscale-archive-keyring.gpg] https://pkgs.tailscale.com/stable/debian {{ ansible_distribution_release|lower }} main"
    filename: tailscale
    state: present
  tags:
    - update_packages

- name: Install tailscale
  apt:
    pkg:
      - tailscale
    state: latest
  tags:
    - update_packages
    - tailscale_configure
  notify:
    - restart tailscaled

- name: Add subnet router to tailscale
  copy:
    src: tailscale/sysctl.conf.j2
    dest: "/etc/sysctl.d/99-tailscale.conf"
    mode: "0644"
  become: true
  tags:
    - tailscale_configure
  notify:
    - restart tailscaled

- name: Start tailscale
  debug:
    msg:
      - Run the following command on {{ ansible_default_ipv4.address }} to start tailscale - "sudo tailscale up --advertise-routes={{ tailscale_subnet }} --qr"
      - Complete the login and then check if the connection is successful by running - "tailscale ip"
      - Run the "tailscale_configure" ansible tag to configure tailscale after login
  tags:
    - manual
