---
# Update this file before running the playbook

# Raspberry Pi configuration
rpi_username: "nirantak"
rpi_password: "change-this-password"
ssh_public_key_url: "https://github.com/nirantak.keys"
rpi_hostname: pie.run
rpi_timezone: Asia/Kolkata
rpi_wifi_country: IN
rpi_locale: en_US.UTF-8
rpi_kb_layout: us

# Setup zsh, ohmyzsh with plugins, dotfiles
customize_shell: true
install_nodejs_version: 18
install_python_version: 3.10.6
install_bat_version: 0.21.0
install_cloudflared_version: 2022.8.0

# Pi-hole configuration
pihole_enable: true
pihole_password: "change-this-password"
pihole_admin_email: "admin@pie.run"
