---
# Update this file before running the playbook

# Raspberry Pi configuration
ssh_public_key_url: "https://github.com/nirantak.keys"
rpi_hostname: pie.run
rpi_timezone: Asia/Kolkata
rpi_wifi_country: IN
rpi_locale: en_US.UTF-8
rpi_kb_layout: us

# Setup zsh, ohmyzsh with plugins, dotfiles
install_custom_shell: true
install_python_version: 3.12.4
install_bat_version: 0.24.0
tailscale_install: true

# Docker configuration
docker_shared_dir: "/home/{{ ansible_user }}/apps"

# Home Assistant configuration
homeassistant_install: true
homeassistant_port: 8123
homeassistant_domain: home.pie.run

# Pi-hole configuration
pihole_install: true
pihole_domain: dns.pie.run
pihole_port: 8080
pihole_password: "change-this-password" # change this to reset pihole admin password
pihole_upstream_dns: "1.1.1.1;1.0.0.1"
pihole_adlist:
  - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
  - https://raw.githubusercontent.com/notracking/hosts-blocklists/master/hostnames.txt
  - https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/hosts.txt
pihole_allowlist:
  - chtbl.com # loads podcasts
  - s.youtube.com # marks YT videos as watched
  - firebaselogging.googleapis.com # causes some mobile apps to fail loading
  - cdn.amplitude.com # causes some websites to fail loading
  - p.typekit.net # loads Adobe fonts
