# Default Config
default_config:

frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# User Config
http:
  server_port: "{{ hast_port }}"
  ip_ban_enabled: true
  login_attempts_threshold: 5
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.0.0.0/8
    - 100.64.0.0/10
    - "{{ tailscale_subnet }}"

homekit:
- name: Homekit Bridge
  port: 21065
  filter:
    include_domains:
      - light
      - fan
