name: rpi

services:

{% if proxy_install %}
# https://doc.traefik.io/traefik/getting-started/quick-start/
  proxy:
    container_name: proxy
    image: traefik:v3.1
    hostname: "{{ proxy_domain }}"
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    volumes:
      - "{{ docker_shared_dir }}/traefik:/etc/traefik/"
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    env_file: .env

    labels:
      - traefik.enable=true
      - traefik.http.routers.proxy.rule=Host(`{{ proxy_domain }}`)
      - traefik.http.routers.proxy.service=api@internal
      - traefik.http.routers.proxy.middlewares=my-auth@file
{% if proxy_cert_resolver %}
      - traefik.http.routers.proxy.tls=true
      - traefik.http.routers.proxy.tls.certresolver=resolver-{{ proxy_cert_resolver }}
{% endif %}
{% endif %}

{% if hast_install %}
# https://www.home-assistant.io/installation/alternative#docker-compose
  home-assistant:
    container_name: home-assistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    hostname: "{{ hast_domain }}"
    volumes:
      - "{{ docker_shared_dir }}/home-assistant:/config"
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
{% endif %}

{% if pihole_install %}
# https://github.com/pi-hole/docker-pi-hole#quick-start
  pihole:
    container_name: pihole
    image: "ghcr.io/pi-hole/pihole:latest"
    hostname: "{{ pihole_domain.split('.')[0] }}"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
{% if not proxy_install %}
      - "{{ pihole_port }}:80/tcp"
{% endif %}
    environment:
      TZ: '{{ rpi_timezone }}'
      WEBPASSWORD: '{{ pihole_password }}'
      FTLCONF_LOCAL_IPV4: '{{ ansible_facts['default_ipv4']['address'] }}'
      PIHOLE_DNS_: '{{ pihole_upstream_dns }}'
      VIRTUAL_HOST: '{{ pihole_domain | default(rpi_hostname, True) }}'
      TEMPERATUREUNIT: 'c'
      WEBTHEME: 'default-auto'
    volumes:
      - "{{ docker_shared_dir }}/pihole/etc-pihole:/etc/pihole"
      - "{{ docker_shared_dir }}/pihole/etc-dnsmasq.d:/etc/dnsmasq.d"
      - /etc/localtime:/etc/localtime:ro
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

{% if proxy_install %}
    labels:
      - traefik.enable=true
      - traefik.http.routers.pihole.rule=Host(`{{ pihole_domain }}`)
      - traefik.http.services.pihole.loadbalancer.server.port=80
{% if proxy_cert_resolver %}
      - traefik.http.routers.pihole.tls=true
      - traefik.http.routers.pihole.tls.certresolver=resolver-{{ proxy_cert_resolver }}
{% endif %}
{% endif %}
{% endif %}
