# Git pre-commit hooks, see https://pre-commit.com

default_language_version:
  python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: check-json
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: pretty-format-json
        args: [--autofix, --no-sort-keys]
