---
extends: default

yaml-files:
  - "*.yaml"
  - "*.yml"
  - ".yamllint.yml"
  - ".ansible-lint"

ignore: |
  .venv/
  roles/elliotweiser.osx-command-line-tools/
  roles/geerlingguy.dotfiles/

rules:
  line-length:
    max: 140
    level: warning
  document-start:
    ignore: |
      .pre-commit-config.yaml
      .github/workflows/*
  truthy:
    ignore: |
      .github/workflows/*
  braces:
    max-spaces-inside: 1
