---
extends: default

yaml-files:
  - "*.yaml"
  - "*.yml"
  - ".yamllint.yml"
  - ".ansible-lint"

ignore: |
  .venv/
  roles/raspberry_pi/templates/

rules:
  line-length:
    max: 160
    level: warning
  document-start:
    ignore: |
      .pre-commit-config.yaml
      .github/workflows/*
  truthy:
    ignore: |
      .github/workflows/*
  braces:
    max-spaces-inside: 1
  comments:
    min-spaces-from-content: 1
