# Traefik - file provider, imported in traefik.yml
http:
  routers:
    home-assistant:
      entryPoints:
        - web
        - websecure
      service: home-assistant
      rule: "Host(`{{ hast_domain }}`)"
{% if proxy_cert_resolver %}
      tls:
        certResolver: resolver-{{ proxy_cert_resolver }}
{% endif %}

  services:
    home-assistant:
      loadBalancer:
        servers:
          - url: "http://{{ hast_domain }}:{{ hast_port }}/"

  middlewares:
    my-auth:
      basicAuth:
        usersFile: "/etc/traefik/proxy-auth.htpasswd"
