# Traefik - static configuration
api:
  dashboard: true

providers:
  docker:
    exposedByDefault: false
  file:
    filename: /etc/traefik/file-provider.yml

log:
  level: WARN

accessLog:
  filters:
    statusCodes:
      - "400-499"
      - "500-599"

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
